# Generated by Django 4.2.5 on 2023-09-09 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_completedassignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedassignment',
            old_name='completed_on',
            new_name='timestamp',
        ),
    ]
