# Generated by Django 4.2.5 on 2023-09-09 05:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0003_rename_completed_on_completedassignment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='completed_by',
            field=models.ManyToManyField(blank=True, related_name='completed_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
